src/test.rs

Branch protection was not set up correctly, so code that failed CI landed in main.
Fix clippy violation in test.
See CI

Fix clippy

---

Cargo.lock
rust-toolchain.toml
samples/internet_identity.did
src/idl2json/Cargo.toml
src/idl2json/examples/init.rs
src/idl2json/src/candid_types.rs
src/idl2json/src/lib.rs
src/idl2json/src/test.rs
src/idl2json/src/typed_conversion.rs
src/idl2json/src/untyped_conversion.rs
src/idl2json_cli/Cargo.toml

It would be nice to have type names in records and variants.  If a did file is available, this can be done on a best-effort basis.
- Bump the candid version to 0.8.1
- Move the untyped idl2json to another file in the library
- Add a typed idl2json to the library
- Add an example to illustrate how the typed conversion works, printing intermediate values.
- Add a `rust_toolchain.toml` as the code doesn't compile with whatever Rust I was using at first.
- Added clippy lints to ensure that the code cannot panic with `panic()`, `unwrap()` or `expect()`.  The conversion should never fail.
- Added a function to convert internal types to IDLTypes, because `#[derive(Candid)]` provides the internal type.
- Added a single "happy path" test for decoding binary candid to JSON with a given schema.
- …

Add a typed idl2json

---

Cargo.lock
src/idl2json/examples/init.rs
src/idl2json/src/lib.rs
src/idl2json/src/polyfill.rs
src/idl2json_cli/Cargo.toml
src/idl2json_cli/src/lib.rs
src/idl2json_cli/src/main.rs

The idl2json library supports converting data with the help of a schema.  This is now also supported on the command line.
Note that a further chnage is needed for this to become really useful:  idl2json needs to support binary input.
- Factor out the IDLProg getter function into a file of polyfills.
- Add flags to allow the user to specify a type and did file
- Use types when converting, if available

feat: Add support for schemas on the command line

---

Cargo.lock
src/idl2json/Cargo.toml
src/idl2json/examples/init.rs
src/idl2json/src/lib.rs
src/idl2json_cli/Cargo.toml
src/idl2json_cli/src/lib.rs
src/idl2json_cli/src/main.rs
src/idl2json_cli/src/tests.rs
src/yaml2candid/Cargo.toml
src/yaml2candid_cli/Cargo.toml

The idl2json command line assumes the common case of a single candid structure:
```
$ echo "( record {} )" | idl2json 
{}
```
however there may be multiple or no structures.  This is currently unsupported.  Effectively this means that the output becomes an array with zero or more entries.  This can be done without breaking backwards compatibility by emitting zero or more JSON structures:
```
$ echo "()" | idl2json 
$ echo "( record {} )" | idl2json 
{}
$ echo "( record {}, record {} )" | ./target/debug/idl2json 
{}
{}
```
- Support an arbitrary number of `IDLValue`s
- Refactor to take a string as input and output of the main library function, to make it testable.
- Add tests
- Bump the cargo version
- Address clippy issues in the existing code

fix: Support vector

---

.github/workflows/rust.yaml
src/idl2json_cli/src/lib.rs
src/idl2json_cli/src/tests.rs

The `idl2json` CLI has no tests.  A previous PR sketched in the tests but:
- The tests were not enabled
- The tests are far from complete.
- Enable the `idl2json_cli` tests file.
- Add tests to bring the code coverage of `idl2json_cli/src/lib.rs` to 100%.  Note, not every combination of branches is covered but every line is exercised at least once.
- Ratchet up the required code coverage in CI.
This PR provides just tests.  They are exercised in CI and the tarpaulin code coverage report is also available in CI.

Enable tests for idl2json_cli

---

Cargo.lock
src/idl2json/Cargo.toml
src/idl2json/examples/init.rs
src/idl2json/src/lib.rs
src/idl2json/src/polyfill.rs
src/idl2json/src/test.rs
src/idl2json/src/typed_conversion.rs
src/idl2json/src/untyped_conversion.rs
src/idl2json_cli/src/lib.rs
src/idl2json_cli/src/tests.rs

We wish to be able to convert proposal arguments to JSON.  This requires:
- Canister arguments are of type IDLArgs which is a vector of types, rather than one IDLType.  Assuming that the argument is just one IDLType leads to errors that have to be handled downstream.  It is better to fix it here, at source.
- Canister arguments often refer to types defined in the did file.  The did file is an IDLProg which has a declarations section, where these types are defined.  Thus we need optional support for providing one (or more) IDLProgs and looking in them for type definitions. If a type is not found, we fall back to unannotated conversion to JSON.
- We need to be able to extract init args from a did file. There is already code for this in the nns-dapp repo that we can steal.
- We also need …

Parse service

---

Cargo.lock
src/idl2json/Cargo.toml
src/idl2json/src/lib.rs
src/idl2json/src/typed_conversion.rs
src/idl2json_cli/Cargo.toml
src/idl2json_cli/src/lib.rs
src/idl2json_cli/src/tests.rs

Proposals contain didc wrapped in didc, so they need to be parsed, then the payload bytes need to be parsed again.  `didc` takes hex as input, so the payload blob is needed as hex, not an array of ints.  The `idl2json` library already supports this, but the option is not exposed in the CLI.
* Expose the idl2json bytes formatting option in the CLI.
Note: The "long bytes" option is not exposed, as the clap for that is complicated and this is not a priority.

Cli bytes as

---

Cargo.lock
src/idl2json/Cargo.toml
src/idl2json/src/lib.rs
src/idl2json_cli/Cargo.toml
src/idl2json_cli/src/lib.rs
src/idl2json_cli/src/tests.rs
src/yaml2candid/Cargo.toml
src/yaml2candid_cli/Cargo.toml

The current compact JSON output is hard to read, frequently making an additional pipe to a formatting tool necessary.
- Offer both pretty and compact output.
- Note: The flag is the same as with `jq` to ease adoption:
```
$ jq --help | grep comp
-c               compact instead of pretty-printed output;
```

Offer compact and pretty output, with pretty being the default

---

Cargo.toml

This warning:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
* Set the resolver to 2.
Existing tests should suffice

chore: Set resolver to 2

---

Cargo.toml
src/idl2json/Cargo.toml
src/idl2json_cli/Cargo.toml

The `idl2json_cli` needs to use the same version of candid as `idl2json`.  Currently, this is enforced only by this comment:
```
candid = "0.8.1" # Should match the version in the lib.
```
We can provide a stronger guarantee that they are the same by providing the candid version in the workspace.
- Define the candid version in the workspace Cargo.toml.
- Use the workspace candid version in `idl2json` and `idl2json_cli`, but not `yaml2candid`.  The last currently uses a different version.  Perhaps it _should_ use the same but it does not.
Existing tests should suffice.

Set the idl2json version in the workspace

---

Cargo.lock
src/yaml2candid/Cargo.toml

`yaml2candid` does not currently use the workspace candid version.  It would be better if it did, so that all the `idl2json` tools used the same version of `candid`.
- Use the workspace version of `candid` for `yaml2candid`.
CI should suffice for most purposes.
For the `yaml2candid` CLI, the change does not take effect until the release version is bumped.  I have tested updating the release version locally.

Use the workspace candid for yaml2candid

---

Cargo.toml

A new minor release of `candid` is available.  The latest `0.8.*` release of candid is `0.8.4`, so this PR ensures that the latest and greatest `0.8.*` series `candid` is supported before we switch to `0.9.*` series releases.

Update candid to 0.8.4

---

Cargo.lock
Cargo.toml
src/idl2json/examples/init.rs
src/idl2json/src/bytes.rs
src/idl2json/src/candid_types.rs
src/idl2json/src/test.rs
src/idl2json/src/typed_conversion.rs
src/idl2json/src/untyped_conversion.rs
src/idl2json_cli/src/lib.rs
src/yaml2candid/src/lib.rs

We would like to support `candid` version `0.9.*`.
- Update `candid` to version `0.9.0`.
- Note: Also tested locally with `candid` `0.9.0` `0.9.4` and `0.9.8`.  It probably makes sense to make a release with v `0.9.0` and another with v `0.9.8`.
Existing tests in CI should suffice.

Update to candid 0.9.0

---

.github/dependabot.yml

Dependabot could take over more of the chores, such as updating GitHub actions.
- Add a dependabot config that specifies:
- To update Rust (cargo) dependencies weekly.
- To update GitHub actions periodically
This same config is used by other repositories I manage, including for example nns-dapp.

feat: Add dependabot config

---

.github/workflows/publish.yml

`cargo publish` takes the pre-release version from `Cargo.toml` and ignores the version taken as a workflow argument.  The one and only way of setting the pre-release version should therefore be to set it in `Cargo.toml`.
- Remove the `prerelease` workflow input.

Do not offer pre-release as a workflow option

---

.github/workflows/publish.yml
Cargo.lock
Cargo.toml
src/idl2json_cli/Cargo.toml
src/yaml2candid_cli/Cargo.toml

- Make the draft GitHub release public once all other steps in the release process have succeeded.
- Bump the alpha version number
- This release was published by this workflow: https://github.com/dfinity/idl2json/releases/tag/v0.9.3-alpha.3

Publish GitHub release after `cargo publish` has succeeded

---

.github/workflows/publish.yml
Cargo.lock
Cargo.toml
HACKING.md
src/idl2json_cli/Cargo.toml
src/yaml2candid_cli/Cargo.toml

We would like a release that uses `candid` version `0.9.x`.  The workflow and feature flags have been overhauled and tested,  so we are ready to proceed.
- Add a `HACKING.md` file.
- Add a progress message to the release flow.
- Update the version from `0.9.3-alpha.3` to `0.9.3`.

Release 0.9.3

---

Cargo.lock
Cargo.toml
src/yaml2candid/Cargo.toml
src/yaml2candid/src/lib.rs
src/yaml2candid/src/test.rs
src/yaml2candid/tests/nns-sns-wasm.rs
src/yaml2candid/tests/nns-sns-wasm/SnsInitPayload.idl

`yaml2candid` is very incomplete and still in some places buggy.  Specifically, it does not support many Candid types and the opt test vectors (and implementation that was guided by those test vectors) are wrong.
- Restructure the main `yaml2json` type match so that the compiler will complain when not all types are matched.
- Add YAML to Candid conversions for almost all missing Candid types.  Service and class are still unsupported.  I am running out of time and these are both complicated and not needed for my immediate goal.
- Add lots of tests.
- Fix the existing test vector that didn't include `opt` in the candid.
- Fairly comprehensive unit tests are included for each individual type.
- Test coverage was checked with Tarpaulin; the tarpaulin report is generated by CI and can be …

Yaml2json types

---

src/yaml2candid/src/lib.rs
src/yaml2candid_cli/src/bin/yaml2candid.rs

If a `yaml2candid` conversion fails to convert some element deep inside a Yaml file into the requested Candid type, the current error message provides no contextual information to communicate where the conversion failed.
For example, if this fails to convert to Candid because the candid spec expects a vector of bytes where we have "man":
```
foo:
bar:
bat: man
```
then the error is:
```
called `Result::unwrap()` on an `Err` value: Expected a sequence for vec type, got: String("man")
```
Add a few more superheroes and it can easily become hard to tell whether the villain in disguise is spiderman, batman aquaman or some other .*man.
Ideally the error message should state on which line and character the conversion failed.  This could be done, theoretically, if the YAML is converted as it is …

fix (yaml2candid): Error message indicates where the conversion failed

---

Cargo.lock
Cargo.toml
src/idl2json/Cargo.toml
src/idl2json_cli/Cargo.toml
src/yaml2candid/Cargo.toml
src/yaml2candid/src/lib.rs
src/yaml2candid/src/test.rs
src/yaml2candid_cli/Cargo.toml

`idl2json` supports encoding blobs as hex but the reverse is not true: `yaml2candid` does not accept byte arrays expressed as hex.  This is inconvenient, to put it mildly.
- Support blobs expressed as hex or base64.
- Unit tests are included with 100% code coverage of the added lines.

feat (yaml2candid): Support blobs input as hex or base64
